### ISSUE TITLE
Enable repoclosure report for more repository

### ISSUE THREAD

**Issue by AngryPenguinPL** [OpenMandrivaSoftware/docker-abf#3]
It would be nice if you could activate [repoclosure report](http://repoclosure.openmandriva.org/) for more repository.
For now repoclosure works only for main repo. If possible, please enable also unsupported, restricted and non-free.

If this is not a problem, you could also enable it for other releases to track Rolling or Rock (4.1+) repositories.

Regards.

**Comment by tpgxyz** [comment]
@AngryPenguinPL If anyone could prepare a HTML page that will handle all the repos etc it would be easier :)

**Comment by fedya** [comment]
need to optimize an entrypoint.sh a bit
https://github.com/OpenMandrivaSoftware/docker-abf/blob/master/abf-repoclosure/entrypoint.sh#L142

**Comment by fedya** [comment]
fixed
